# Generated by Django 3.2.6 on 2021-08-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(blank=True, default='', max_length=256)),
                ('content', models.TextField(blank=True, default='')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
