# Generated by Django 3.2.4 on 2021-08-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, default="", max_length=256)),
                ("posts", models.ManyToManyField(related_name="tags", to="posts.Post")),
            ],
        ),
    ]
