# Generated by Django 3.2.4 on 2021-08-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_post_created"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="id",
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(blank=True, default="", max_length=256, primary_key=True, serialize=False),
        ),
    ]
