# Generated by Django 3.2.4 on 2021-08-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_remove_tag_posts"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="posts",
            field=models.ManyToManyField(related_name="tags", to="posts.Post"),
        ),
    ]
